提交

diff --git a/service/client_centos b/service/client_centos
--- a/service/client_centos
+++ b/service/client_centos
@@ -1,9 +1,16 @@
 #!/bin/bash
 
 NAME="ServerStatusPlus 客户端"
+NAMEP="ping 客户端"
 NAME_BIN="status-plus-client.py"
+NAME_BINP="status-ping.py"
 if [[ -e "/usr/local/ServerStatusPlus/status-plus-client.py" ]]; then
 	BIN="/usr/local/ServerStatusPlus/status-plus-client.py"
+else
+	echo -e "${Error_font_prefix}[错误]${Font_suffix} 客户端文件($NAME_BIN)找不到 !" && exit 1
+fi
+if [[ -e "/usr/local/ServerStatusPlus/status-ping.py" ]]; then
+	BINP="/usr/local/ServerStatusPlus/status-ping.py"
 else
 	echo -e "${Error_font_prefix}[错误]${Font_suffix} 客户端文件($NAME_BIN)找不到 !" && exit 1
 fi
@@ -12,6 +19,14 @@ RETVAL=0
 
 check_running(){
 	PID=`ps -ef |grep "${NAME_BIN}" |grep -v "grep" |grep -v "init.d" |grep -v "service" |awk '{print $2}'`
+	if [[ ! -z ${PID} ]]; then
+		return 0
+	else
+		return 1
+	fi
+}
+check_running_ping(){
+	PID=`ps -ef |grep "${NAME_BINP}" |grep -v "grep" |grep -v "init.d" |grep -v "service" |awk '{print $2}'`
 	if [[ ! -z ${PID} ]]; then
 		return 0
 	else
@@ -33,6 +48,21 @@ do_start(){
 			echo -e "${Error_font_prefix}[错误]${Font_suffix} $NAME 启动失败 !"
 		fi
 	fi
+	
+	check_running_ping
+	if [[ $? -eq 0 ]]; then
+		echo -e "${Info_font_prefix}[信息]${Font_suffix} $NAMEP (PID ${PID}) 正在运行..." && exit 0
+	else
+		ulimit -n 51200
+		nohup python3 "$BINP" > /usr/local/ServerStatusPlus/log/ping.log 2>&1 &
+		sleep 2s
+		check_running_ping
+		if [[ $? -eq 0 ]]; then
+			echo -e "${Info_font_prefix}[信息]${Font_suffix} $NAMEP 启动成功 !"
+		else
+			echo -e "${Error_font_prefix}[错误]${Font_suffix} $NAMEP 启动失败 !"
+		fi
+	fi
 }
 do_stop(){
 	check_running
@@ -48,6 +78,20 @@ do_stop(){
 		echo -e "${Info_font_prefix}[信息]${Font_suffix} $NAME 未运行"
 		RETVAL=1
 	fi
+
+	check_running_ping
+	if [[ $? -eq 0 ]]; then
+		kill -9 ${PID}
+		RETVAL=$?
+		if [[ $RETVAL -eq 0 ]]; then
+			echo -e "${Info_font_prefix}[信息]${Font_suffix} $NAMEP 停止成功 !"
+		else
+			echo -e "${Error_font_prefix}[错误]${Font_suffix} $NAMEP 停止失败 !"
+		fi
+	else
+		echo -e "${Info_font_prefix}[信息]${Font_suffix} $NAMEP 未运行"
+		RETVAL=1
+	fi
 }
 do_status(){
 	check_running
@@ -55,6 +99,14 @@ do_status(){
 		echo -e "${Info_font_prefix}[信息]${Font_suffix} $NAME (PID ${PID}) 正在运行..."
 	else
 		echo -e "${Info_font_prefix}[信息]${Font_suffix} $NAME 未运行 !"
+		RETVAL=1
+	fi
+
+	check_running_ping
+	if [[ $? -eq 0 ]]; then
+		echo -e "${Info_font_prefix}[信息]${Font_suffix} $NAMEP (PID ${PID}) 正在运行..."
+	else
+		echo -e "${Info_font_prefix}[信息]${Font_suffix} $NAMEP 未运行 !"
 		RETVAL=1
 	fi
 }
